#Configuração do Banco de Dados - SISPOLI
#Fri Apr 10 15:25:24 BRT 2026
db.encrypt=false
db.pass=1202153120
db.url=jdbc\:mariadb\://192.168.18.250/gestao_ginasio?useSSL\=false&serverTimezone\=UTC
db.user=robson
